//* eslint-disable camelcase, @typescript-eslint/no-unused-vars */
// This file is normally generated by `@laravel/vite-plugin-wayfinder` when
// `routes: true` is enabled in `vite.config.ts`.  It provides strongly-typed
// helper functions that return URLs for named Laravel routes.  During
// development the plugin will overwrite this file; the stub below ensures
// the module exists so TypeScript doesn't complain when editing.


/**
 * We wrap the Ziggy 'route' helper to provide a clean
 * interface for your React components.
 */

const safeRoute = (name: string, fallback = '/') => {
  const routeFn = (window as any).route;
  if (typeof routeFn !== 'function') {
    return fallback;
  }

  try {
    return routeFn(name);
  } catch {
    return fallback;
  }
};

export const login = () => safeRoute('login', '/login');
export const register = () => safeRoute('register', '/register');
export const dashboard = () => safeRoute('dashboard', '/dashboard');
export const home = () => safeRoute('home', '/');
export const logout = () => safeRoute('logout', '/logout');

// The plugin will append other named routes automatically.  You can run
// `npm run dev` or `npm run build` to regenerate the full list.

// Manually added student routes
export const studentInformation = () => (window as any).route('student.information');
export const studentHistory = () => (window as any).route('student.history');
export const studentRequestCreate = () => (window as any).route('student.requests.create');
// export const studentRequestsShow = (id: number) => (window as any).route('student.requests.show', id);

// Admin Routes
export const adminDashboard = () => (window as any).route('admin.dashboard');
export const adminRequests = () => (window as any).route('admin.requests.index');

export default {
    dashboard,
    login,
    register,
    home,
    logout,
};
